rent/rent/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

]

urlpatterns += i18n_patterns(
    path("", include("webapp.urls")),
    path("accounts/", include("accounts.urls"))
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rent/webapp/urls.py
from django.urls import path
from webapp.views import general_view, car_view

app_name = "webapp"

urlpatterns = [
    path('', general_view.IndexView.as_view(), name="index"),
    path('about_us/', general_view.AboutUsView.as_view(), name="about_us"),
    path('cars/', car_view.CarListView.as_view(), name="car_list"),
    path('cars/<int:pk>/', car_view.CarDetailView.as_view(), name="car_detail"),
    path('contacts/', general_view.ContactView.as_view(), name="contacts"),
    path('cars/<int:pk>/review/create/', car_view.ReviewCreateView.as_view(), name="review_create"),
    path('cars/new/', car_view.CarCreateView.as_view(), name="car_create"),
    path('cars/<int:pk>/delete/', car_view.CarDeleteView.as_view(), name="car_delete"),
    path('cars/<int:pk>/photo/new/', car_view.PhotoCreateView.as_view(), name="photo_create")
]

rent/webapp/models.py
from django.db import models
from django.contrib.auth import get_user_model
from phonenumber_field.modelfields import PhoneNumberField
from django.utils.translation import gettext_lazy as _


class Car(models.Model):
    model = models.CharField(max_length=30, null=False, blank=False, verbose_name=_("Model"))
    volume = models.DecimalField(max_digits=3, decimal_places=2, null=False, blank=False, verbose_name=_("Vol"))
    year = models.DateField(blank=False, null=False)
    fuel = models.CharField(max_length=30, blank=True, null=True, verbose_name=_("Fuel"))
    platform = models.ForeignKey("webapp.Platform", on_delete=models.PROTECT, verbose_name=_("Platform"),
                                 related_name="cars")

    def __str__(self):
        return f"{self.model} - {self.fuel} - {self.platform}"


class Photo(models.Model):
    photo = models.ImageField(null=True, blank=True, upload_to="photos", verbose_name=_("Photo"))
    car = models.ForeignKey("webapp.Car", null=False, blank=False, on_delete=models.CASCADE, verbose_name=_("Car"),
                            related_name="photos")

    def __str__(self):
        return f"{self.pk}"


class Platform(models.Model):
    name = models.CharField(max_length=30, null=False, blank=False, verbose_name=_("Model"))
    length = models.PositiveSmallIntegerField(blank=False, null=False, verbose_name=_("LongPla"))
    width = models.PositiveSmallIntegerField(blank=False, null=False, verbose_name=_("WidthPla"))
    height = models.PositiveSmallIntegerField(blank=False, null=False, verbose_name=_("HeightPla"))

    def __str__(self):
        return f"{self.name}"


class Review(models.Model):
    car = models.ForeignKey("webapp.Car", on_delete=models.CASCADE, verbose_name=_("Model"), related_name="reviews")
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, verbose_name=_("Author"), related_name="reviews")
    text = models.TextField(max_length=500, verbose_name=_("Review"))
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.car} - {self.author}"


class Client(models.Model):
    author = models.ForeignKey(get_user_model(), verbose_name=_('Author'), related_name='clients', on_delete=models.PROTECT)
    phone = PhoneNumberField(blank=True, verbose_name=_("Phone"))
    email = models.EmailField(null=True, blank=True, verbose_name=_("Email"))
    message = models.CharField(max_length=3000, null=False, blank=False, verbose_name=_("Message"))
    created_at = models.DateTimeField(auto_now=True)

rent/webapp/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django import forms

from webapp.models import Client, Car, Photo


class ClientForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'

        self.helper.add_input(Submit('submit', 'Submit'))

    class Meta:
        model = Client
        exclude = ['created_at', 'author']


class CarForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'

        self.helper.add_input(Submit('submit', 'Submit'))

    class Meta:
        model = Car
        exclude = ['']


class PhotoForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'

        self.helper.add_input(Submit('submit', 'Submit'))

    class Meta:
        model = Photo
        exclude = ['']

rent/webapp/views.py
from django.shortcuts import render

# Create your views here.

rent/webapp/views/car_view.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic import DetailView, CreateView, DeleteView, ListView

from webapp.forms import CarForm, PhotoForm
from webapp.models import Car, Review, Photo


class CarListView(ListView):
    model = Car
    template_name = "cars/list.html"
    ordering = ["year"]
    context_object_name = "cars"


class CarDetailView(DetailView):
    model = Car
    template_name = "cars/detail.html"
    context_object_name = "car"
    pk_url_kwarg = "pk"


class ReviewCreateView(LoginRequiredMixin, CreateView):
    model = Review
    template_name = 'partial/review_form.html'
    fields = ['text']

    def form_valid(self, form):
        form.instance.car = self.get_object()
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_object(self, queryset=None):
        pk = self.kwargs.get("pk")
        return get_object_or_404(Car, pk=pk)

    def get_success_url(self):
        return reverse('webapp:car_detail', kwargs={"pk": self.object.car.pk})


class CarCreateView(PermissionRequiredMixin, CreateView):
    model = Car
    form_class = CarForm
    template_name = "cars/create.html"
    permission_required = "webapp.add_car"

    def get_form(self, form_class=None):
        form = super().get_form()
        form.helper.form_action = 'webapp:car_create'
        return form

    def get_object(self, queryset=None):
        pk = self.kwargs.get("pk")
        return get_object_or_404(Car, pk=pk)

    def get_success_url(self):
        return reverse('webapp:car_detail', kwargs={"pk": self.object.pk})


class CarDeleteView(PermissionRequiredMixin, DeleteView):
    model = Car
    template_name = "cars/delete.html"
    success_url = reverse_lazy("webapp:index")
    permission_required = "webapp.delete_car"


class PhotoCreateView(PermissionRequiredMixin, CreateView):
    model = Photo
    template_name = "cars/photo_form.html"
    form_class = PhotoForm
    permission_required = "webapp.add_photo"

    def form_valid(self, form):
        form.instance.car = self.get_object()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context["pk"] = self.kwargs.get("pk")
        return context

    def get_object(self, queryset=None):
        pk = self.kwargs.get("pk")
        return get_object_or_404(Car, pk=pk)

    def get_success_url(self):
        return reverse('webapp:car_detail', kwargs={"pk": self.object.car.pk})

rent/webapp/views/general_view.py
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import View, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin

from webapp.forms import ClientForm
from webapp.models import Client


class IndexView(View):
    def get(self, request, *args, **kwargs):
        return render(request, "general/index.html")


class AboutUsView(View):
    def get(self, request, *args, **kwargs):
        return render(request, "general/about_us.html")


class ContactView(LoginRequiredMixin, CreateView):
    model = Client
    template_name = 'general/contacts.html'
    form_class = ClientForm

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_form(self, form_class=None):
        form = super().get_form()
        form.helper.form_action = 'webapp:contacts'
        return form

    def get_success_url(self):
        return reverse('webapp:index')

rent/webapp/templates/partial/advantages.html
{% load i18n %}
<div class="d-flex flex-column align-items-center mt-5">
        <h1 class="title_advantages mt-5">{% trans "Perfect" %}</h1>
        <p>
            {% blocktrans %}Наш опыт и репутация – самые важные показатели, но есть еще несколько важных условий{% endblocktrans %}:
        </p>
    </div>
   <div class="collapse_advantages">
        <h3 class="">1 {% blocktrans %}Собственный автопарк{% endblocktrans %}</h3>
        <p class="text-secondary">{% blocktrans %}В моменты пиковых нагрузок, очень важно иметь резервные варианты{% endblocktrans %}</p>

        <h3 class="mt-3">2 {% blocktrans %}Квалифицированный персонал{% endblocktrans %} </h3>
            <p class="text-secondary">{% blocktrans %}Слаженная работа механиков, персональных менеджеров{% endblocktrans %},<br>
                {% blocktrans %}бухгалтеров и юристов – залог высокого сервиса обслуживания{% endblocktrans %}. <br>
                {% blocktrans %}Персональный менеджер учтет все Ваши пожелания и проследит за работой команды{% endblocktrans %}.</p>

        <h3 class="mt-3">3 {% blocktrans %}Система мониторинга транспорта {% endblocktrans %}</h3>
            <p class="text-secondary">{% blocktrans %}Современное оборудование GPS-навигации позволяет эффективно {% endblocktrans %}<br>
                {% blocktrans %}и своевременно отслеживать транспорт на пути его следования{% endblocktrans %}</p>

        <h3 class="mt-3">4{% blocktrans %} Полная документальная и юридическая безопасность{% endblocktrans %} </h3>
            <p class="text-secondary">{% blocktrans %}Мы предоставляем полный пакет документов{% endblocktrans %}, <br>
                {% blocktrans %}заключаем договора согласно Законодательству Республики Казахстан{% endblocktrans %}, <br>
                {% blocktrans %}прозрачно и понятно ведем сделку с нашими клиентами{% endblocktrans %}.</p>

        <h3 class="mt-3">5{% blocktrans %} Полностью оснащенная материально-техническая база СТО {% endblocktrans %}<br></h3>
            <p class="text-secondary">{% blocktrans %}Все автомобили проходят постоянный контроль на авторизованном СТО{% endblocktrans %},<br>
                {% blocktrans %}имеются 3 СТО и охраняемая база{% endblocktrans %}</p>
   </div>

rent/webapp/templates/partial/client_form.html
{% load crispy_forms_filters %}
{% load i18n %}
<form action="{% url 'webapp:contacts' %}" method="post">
    {% csrf_token %}
    <div class="d-flex flex-column">
        {{ form|crispy }}
        <p class="d-block my-5">*{% blocktrans %} Отправляя форму, вы даете свое согласие на обработку {% endblocktrans %}<br>{% blocktrans %} персональных данных{% endblocktrans %}</p>
        <button  class="btn btn-outline-dark button_client" type="submit">{% trans "sendBtn" %}</button>
    </div>
</form>

rent/webapp/templates/partial/pagination.html
<div class="pagination">
    <span class="step_links">
        {% if page_obj.has_previous %}
            <a href="?{% if query %}{{ query }}&{% endif %}page=1">To start</a>
            <a href="?{% if query %}{{ query }}&{% endif %}page={{ page_obj.previous_page_number }}">
                Back
            </a>
        {% endif %}

        <form action="" method="get">
            <label>
                <input
                        type="number"
                        name="page"
                        value="{{ page_obj.number }}"
                >
                of {{ page_obj.paginator.num_pages }}
            </label>
        </form>

        {% if page_obj.has_next %}
            <a href="?{% if query %}{{ query }}&{% endif %}page={{ page_obj.next_page_number }}">
                Next
            </a>
        {% endif %}

        <a href="?{% if query %}{{ query }}&{% endif %}page={{ page_obj.paginator.num_pages }}">
            To end
        </a>
    </span>
</div>

rent/webapp/templates/partial/review_form.html
{% load i18n %}
<form action="{% url 'webapp:review_create' car.pk %}" method="post">
    {% csrf_token %}
    <div class="d-flex justify-content-between align-items-between">
        <input style="height: 50px; margin-right: 5px;" class="d-block input_review" name="text"
               type="text" placeholder="Оставить отзыв">
        <button  class="btn btn-outline-dark" type="submit">{% trans "CommentBtn" %}</button>
    </div>
</form>