rent/accounts/urls.py
from django.urls import path
from accounts import views as accounts_views

app_name = "accounts"

urlpatterns = [
    path("login/", accounts_views.LoginView.as_view(), name="login"),
    path("logout/", accounts_views.LogoutView.as_view(), name="logout"),
    path("create/", accounts_views.RegisterView.as_view(), name="register"),
    path("<int:pk>/", accounts_views.UserDetailView.as_view(), name="profile"),
    path("profile/<int:pk>/edit", accounts_views.UserChangeView.as_view(), name="edit_profile"),
    path("profile/<int:pk>/change_password", accounts_views.ChangePasswordView.as_view(), name="change_password")
]

rent/rent/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

]

urlpatterns += i18n_patterns(
    path("", include("webapp.urls")),
    path("accounts/", include("accounts.urls"))
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rent/webapp/urls.py
from django.urls import path
from webapp.views import general_view, car_view

app_name = "webapp"

urlpatterns = [
    path('', general_view.IndexView.as_view(), name="index"),
    path('about_us/', general_view.AboutUsView.as_view(), name="about_us"),
    path('cars/', car_view.CarListView.as_view(), name="car_list"),
    path('cars/<int:pk>/', car_view.CarDetailView.as_view(), name="car_detail"),
    path('contacts/', general_view.ContactView.as_view(), name="contacts"),
    path('cars/<int:pk>/review/create/', car_view.ReviewCreateView.as_view(), name="review_create"),
    path('cars/new/', car_view.CarCreateView.as_view(), name="car_create"),
    path('cars/<int:pk>/delete/', car_view.CarDeleteView.as_view(), name="car_delete"),
    path('cars/<int:pk>/photo/new/', car_view.PhotoCreateView.as_view(), name="photo_create")
]

rent/webapp/models.py
from django.db import models
from django.contrib.auth import get_user_model
from phonenumber_field.modelfields import PhoneNumberField
from django.utils.translation import gettext_lazy as _


class Car(models.Model):
    model = models.CharField(max_length=30, null=False, blank=False, verbose_name=_("Model"))
    volume = models.DecimalField(max_digits=3, decimal_places=2, null=False, blank=False, verbose_name=_("Vol"))
    year = models.DateField(blank=False, null=False)
    fuel = models.CharField(max_length=30, blank=True, null=True, verbose_name=_("Fuel"))
    platform = models.ForeignKey("webapp.Platform", on_delete=models.PROTECT, verbose_name=_("Platform"),
                                 related_name="cars")

    def __str__(self):
        return f"{self.model} - {self.fuel} - {self.platform}"


class Photo(models.Model):
    photo = models.ImageField(null=True, blank=True, upload_to="photos", verbose_name=_("Photo"))
    car = models.ForeignKey("webapp.Car", null=False, blank=False, on_delete=models.CASCADE, verbose_name=_("Car"),
                            related_name="photos")

    def __str__(self):
        return f"{self.pk}"


class Platform(models.Model):
    name = models.CharField(max_length=30, null=False, blank=False, verbose_name=_("Model"))
    length = models.PositiveSmallIntegerField(blank=False, null=False, verbose_name=_("LongPla"))
    width = models.PositiveSmallIntegerField(blank=False, null=False, verbose_name=_("WidthPla"))
    height = models.PositiveSmallIntegerField(blank=False, null=False, verbose_name=_("HeightPla"))

    def __str__(self):
        return f"{self.name}"


class Review(models.Model):
    car = models.ForeignKey("webapp.Car", on_delete=models.CASCADE, verbose_name=_("Model"), related_name="reviews")
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, verbose_name=_("Author"), related_name="reviews")
    text = models.TextField(max_length=500, verbose_name=_("Review"))
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.car} - {self.author}"


class Client(models.Model):
    author = models.ForeignKey(get_user_model(), verbose_name=_('Author'), related_name='clients', on_delete=models.PROTECT)
    phone = PhoneNumberField(blank=True, verbose_name=_("Phone"))
    email = models.EmailField(null=True, blank=True, verbose_name=_("Email"))
    message = models.CharField(max_length=3000, null=False, blank=False, verbose_name=_("Message"))
    created_at = models.DateTimeField(auto_now=True)

rent/webapp/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django import forms

from webapp.models import Client, Car, Photo


class ClientForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'

        self.helper.add_input(Submit('submit', 'Submit'))

    class Meta:
        model = Client
        exclude = ['created_at', 'author']


class CarForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'

        self.helper.add_input(Submit('submit', 'Submit'))

    class Meta:
        model = Car
        exclude = ['']


class PhotoForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'

        self.helper.add_input(Submit('submit', 'Submit'))

    class Meta:
        model = Photo
        exclude = ['']

rent/webapp/views.py
from django.shortcuts import render

# Create your views here.

rent/webapp/views/car_view.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic import DetailView, CreateView, DeleteView, ListView

from webapp.forms import CarForm, PhotoForm
from webapp.models import Car, Review, Photo


class CarListView(ListView):
    model = Car
    template_name = "cars/list.html"
    ordering = ["year"]
    context_object_name = "cars"


class CarDetailView(DetailView):
    model = Car
    template_name = "cars/detail.html"
    context_object_name = "car"
    pk_url_kwarg = "pk"


class ReviewCreateView(LoginRequiredMixin, CreateView):
    model = Review
    template_name = 'partial/review_form.html'
    fields = ['text']

    def form_valid(self, form):
        form.instance.car = self.get_object()
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_object(self, queryset=None):
        pk = self.kwargs.get("pk")
        return get_object_or_404(Car, pk=pk)

    def get_success_url(self):
        return reverse('webapp:car_detail', kwargs={"pk": self.object.car.pk})


class CarCreateView(PermissionRequiredMixin, CreateView):
    model = Car
    form_class = CarForm
    template_name = "cars/create.html"
    permission_required = "webapp.add_car"

    def get_form(self, form_class=None):
        form = super().get_form()
        form.helper.form_action = 'webapp:car_create'
        return form

    def get_object(self, queryset=None):
        pk = self.kwargs.get("pk")
        return get_object_or_404(Car, pk=pk)

    def get_success_url(self):
        return reverse('webapp:car_detail', kwargs={"pk": self.object.pk})


class CarDeleteView(PermissionRequiredMixin, DeleteView):
    model = Car
    template_name = "cars/delete.html"
    success_url = reverse_lazy("webapp:index")
    permission_required = "webapp.delete_car"


class PhotoCreateView(PermissionRequiredMixin, CreateView):
    model = Photo
    template_name = "cars/photo_form.html"
    form_class = PhotoForm
    permission_required = "webapp.add_photo"

    def form_valid(self, form):
        form.instance.car = self.get_object()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context["pk"] = self.kwargs.get("pk")
        return context

    def get_object(self, queryset=None):
        pk = self.kwargs.get("pk")
        return get_object_or_404(Car, pk=pk)

    def get_success_url(self):
        return reverse('webapp:car_detail', kwargs={"pk": self.object.car.pk})

rent/webapp/views/general_view.py
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import View, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin

from webapp.forms import ClientForm
from webapp.models import Client


class IndexView(View):
    def get(self, request, *args, **kwargs):
        return render(request, "general/index.html")


class AboutUsView(View):
    def get(self, request, *args, **kwargs):
        return render(request, "general/about_us.html")


class ContactView(LoginRequiredMixin, CreateView):
    model = Client
    template_name = 'general/contacts.html'
    form_class = ClientForm

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_form(self, form_class=None):
        form = super().get_form()
        form.helper.form_action = 'webapp:contacts'
        return form

    def get_success_url(self):
        return reverse('webapp:index')

rent/webapp/templates/cars/create.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% load i18n %}

{% block content %}
    <h1>{% trans "AddCar" %}</h1>
    <form action="{% url "webapp:car_create" %}" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button>{% trans "AddBtn" %}</button>
    </form>
{% endblock %}

rent/webapp/templates/cars/delete.html
{% extends "base.html" %}
{% load i18n %}

{% block content%}
    <h1>{% blocktrans %}Вы действительно хотите удалить {% endblocktrans %} {{ car.model }}?</h1>
    <a href="{% url "webapp:index" %}">{% trans "CancelLink" %}</a>
    <form action="{% url "webapp:car_delete" car.pk %}" method="post">
        {% csrf_token %}
        <button>{% trans "YesBtn" %}</button>
    </form>
{% endblock %}

rent/webapp/templates/cars/detail.html
{% extends "base.html" %}
{% load i18n %}

{% block carousel %}
    <img src="{{ car.photos.first.photo.url }}" class="d-block img_detail w-100" height=700px  alt="фото">
{% endblock %}

{% block content %}
    <div class="text-center">
        <h1>{% blocktrans %}Арендовать автомобиль {% endblocktrans %}<br>
            <small>{{ car.model }} {{ car.year|date:"Y" }}{% trans "year"%}</small>
        </h1>
    </div>
    <div class="d-flex justify-content-between align-items-start my-5">
        <div>
            <h3>{% trans "ParamCarTitle" %}:</h3>
            <p>{% trans "Model" %}: {{ car.model }}</p>
            <p>{% trans "Vol" %}: {{ car.volume }}</p>
            <p>{% trans "Year" %}: {{ car.year|date:"Y" }}</p>
            <p>{% trans "Fuel" %}: {{ car.fuel }}</p>
            <p>{% trans "Platform" %}: {{ car.platform.name }}</p>
        </div>
        <div>
            <h3>{% trans "Platform" %}:</h3>
            <p>{% trans "WidthPla" %}: {{ car.platform.width }}</p>
            <p>{% trans "LongPla" %}: {{ car.platform.length }}</p>
            <p>{% trans "HeightPla" %}: {{ car.platform.height }}</p>
        </div>
        <div>
            <h3>{% trans "Price" %}:</h3>
            {% if car.platform.name == "Цельнометаллическая" %}
                <p>от 9000тг\сутки {% trans "NoDriver" %}</p>
                <p>от 2500тг\час {% trans "WithDriver" %}</p>
            {% else %}
                <p>от 12000тг\сутки {% trans "NoDriver" %}</p>
                <p>от 3500тг\час {% trans "WithDriver" %}<</p>
            {% endif %}
        </div>
    </div>
        <div class="d-flex justify-content-between w-25">
            {% if perms.webapp.add_photo %}
                <a href="{% url "webapp:photo_create" car.pk %}" class="border border-radius-1 p-3 bg-secondary text-white">
                    {% trans "Photo" %}
                </a>
            {% endif %}
            {% if perms.webapp.delete_car %}
                <a href="{% url "webapp:car_delete" car.pk %}" class="border border-radius-1 p-3 bg-secondary text-white">
                     {% trans "DeleteLink" %}
                </a>
            {% endif %}
        </div>
    <div class="d-flex w-100 justify-content-between my-5">
        {% for photo in car.photos.all %}
            <div id="statya">
               <img class="img_pic" src="{{ photo.photo.url }}" alt="pic">
            </div>
        {% endfor %}
    </div>
    <div class="my-5">
        <hr>
        {% if user.is_authenticated %}
            {% include "partial/review_form.html" %}
        <hr>
        {% endif %}
    </div>
    <div>
        <h1>Отзывы:</h1>
        {% for review in car.reviews.all %}
            <div class="my-5">
                <p class="fw-3">
                    {% if user.is_authenticated %}
                        <a href="{% url "accounts:profile" review.author.pk %}" class="text-dark">
                        {{ review.author }}</a>:
                    {% else %}
                        <p>{{ review.author }}</p>
                    {% endif %}
                    <small>{{ review.text }}</small>
                </p>
                <p class="datetime">Дата: {{ review.created_at }}</p>
                <hr>
            </div>
        {% endfor %}
    </div>
{% endblock %}

rent/webapp/templates/cars/list.html
{% extends "base.html" %}
{% load i18n %}

{% block carousel %}
    <img src="https://грузотакси-газелька70.рф/wp-content/uploads/2020/11/4f08.jpg" class="d-block w-100"  alt="фото">
{% endblock %}

{% block content %}
    {% if perms.webapp.add_car %}
        <div class="my-5 text-center">
            <a href="{% url "webapp:car_create" %}" class="border border-radius-1 p-3 bg-secondary text-white">
                {% trans "AddNewCar" %}
            </a>
        </div>
    {% endif %}
    <div class="d-flex flex-wrap justify-content-between mt-5">
        {% for car in cars %}
            <div class="car_list mt-3 ">
                <div class="card" style="width: 18rem;">
                    <img src="{{ car.photos.first.photo.url }}" class="card-img-top border border-2" width=200px height=280px alt="аватарка">
                    <div class="card-body">
                    <h5 class="card-title">{{ car.model }}</h5>
                    <p class="card-text">{% trans "Platform" %}: {{ car.platform }}</p>
                    <a href="{% url "webapp:car_detail" car.pk %}" class="border border-radius-5
                    p-2 bg-info text-white">{% trans "DetailLink" %}</a>
                  </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

rent/webapp/templates/cars/photo_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% load i18n %}

{% block content %}
    <h1>{% trans "AddPhotoTitle" %}</h1>
    <form action="{% url "webapp:photo_create" pk %}" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button>{% trans "AddBtn" %}</button>
    </form>
{% endblock %}