rent/accounts/urls.py
from django.urls import path
from accounts import views as accounts_views

app_name = "accounts"

urlpatterns = [
    path("login/", accounts_views.LoginView.as_view(), name="login"),
    path("logout/", accounts_views.LogoutView.as_view(), name="logout"),
    path("create/", accounts_views.RegisterView.as_view(), name="register"),
    path("<int:pk>/", accounts_views.UserDetailView.as_view(), name="profile"),
    path("profile/<int:pk>/edit", accounts_views.UserChangeView.as_view(), name="edit_profile"),
    path("profile/<int:pk>/change_password", accounts_views.ChangePasswordView.as_view(), name="change_password")
]

rent/rent/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

]

urlpatterns += i18n_patterns(
    path("", include("webapp.urls")),
    path("accounts/", include("accounts.urls"))
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rent/webapp/urls.py
from django.urls import path
from webapp.views import general_view, car_view

app_name = "webapp"

urlpatterns = [
    path('', general_view.IndexView.as_view(), name="index"),
    path('about_us/', general_view.AboutUsView.as_view(), name="about_us"),
    path('cars/', car_view.CarListView.as_view(), name="car_list"),
    path('cars/<int:pk>/', car_view.CarDetailView.as_view(), name="car_detail"),
    path('contacts/', general_view.ContactView.as_view(), name="contacts"),
    path('cars/<int:pk>/review/create/', car_view.ReviewCreateView.as_view(), name="review_create"),
    path('cars/new/', car_view.CarCreateView.as_view(), name="car_create"),
    path('cars/<int:pk>/delete/', car_view.CarDeleteView.as_view(), name="car_delete"),
    path('cars/<int:pk>/photo/new/', car_view.PhotoCreateView.as_view(), name="photo_create")
]

rent/webapp/models.py
from django.db import models
from django.contrib.auth import get_user_model
from phonenumber_field.modelfields import PhoneNumberField
from django.utils.translation import gettext_lazy as _


class Car(models.Model):
    model = models.CharField(max_length=30, null=False, blank=False, verbose_name=_("Model"))
    volume = models.DecimalField(max_digits=3, decimal_places=2, null=False, blank=False, verbose_name=_("Vol"))
    year = models.DateField(blank=False, null=False)
    fuel = models.CharField(max_length=30, blank=True, null=True, verbose_name=_("Fuel"))
    platform = models.ForeignKey("webapp.Platform", on_delete=models.PROTECT, verbose_name=_("Platform"),
                                 related_name="cars")

    def __str__(self):
        return f"{self.model} - {self.fuel} - {self.platform}"


class Photo(models.Model):
    photo = models.ImageField(null=True, blank=True, upload_to="photos", verbose_name=_("Photo"))
    car = models.ForeignKey("webapp.Car", null=False, blank=False, on_delete=models.CASCADE, verbose_name=_("Car"),
                            related_name="photos")

    def __str__(self):
        return f"{self.pk}"


class Platform(models.Model):
    name = models.CharField(max_length=30, null=False, blank=False, verbose_name=_("Model"))
    length = models.PositiveSmallIntegerField(blank=False, null=False, verbose_name=_("LongPla"))
    width = models.PositiveSmallIntegerField(blank=False, null=False, verbose_name=_("WidthPla"))
    height = models.PositiveSmallIntegerField(blank=False, null=False, verbose_name=_("HeightPla"))

    def __str__(self):
        return f"{self.name}"


class Review(models.Model):
    car = models.ForeignKey("webapp.Car", on_delete=models.CASCADE, verbose_name=_("Model"), related_name="reviews")
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, verbose_name=_("Author"), related_name="reviews")
    text = models.TextField(max_length=500, verbose_name=_("Review"))
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.car} - {self.author}"


class Client(models.Model):
    author = models.ForeignKey(get_user_model(), verbose_name=_('Author'), related_name='clients', on_delete=models.PROTECT)
    phone = PhoneNumberField(blank=True, verbose_name=_("Phone"))
    email = models.EmailField(null=True, blank=True, verbose_name=_("Email"))
    message = models.CharField(max_length=3000, null=False, blank=False, verbose_name=_("Message"))
    created_at = models.DateTimeField(auto_now=True)

rent/webapp/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django import forms

from webapp.models import Client, Car, Photo


class ClientForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'

        self.helper.add_input(Submit('submit', 'Submit'))

    class Meta:
        model = Client
        exclude = ['created_at', 'author']


class CarForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'

        self.helper.add_input(Submit('submit', 'Submit'))

    class Meta:
        model = Car
        exclude = ['']


class PhotoForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'

        self.helper.add_input(Submit('submit', 'Submit'))

    class Meta:
        model = Photo
        exclude = ['']

rent/webapp/views.py
from django.shortcuts import render

# Create your views here.

rent/webapp/views/car_view.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic import DetailView, CreateView, DeleteView, ListView

from webapp.forms import CarForm, PhotoForm
from webapp.models import Car, Review, Photo


class CarListView(ListView):
    model = Car
    template_name = "cars/list.html"
    ordering = ["year"]
    context_object_name = "cars"


class CarDetailView(DetailView):
    model = Car
    template_name = "cars/detail.html"
    context_object_name = "car"
    pk_url_kwarg = "pk"


class ReviewCreateView(LoginRequiredMixin, CreateView):
    model = Review
    template_name = 'partial/review_form.html'
    fields = ['text']

    def form_valid(self, form):
        form.instance.car = self.get_object()
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_object(self, queryset=None):
        pk = self.kwargs.get("pk")
        return get_object_or_404(Car, pk=pk)

    def get_success_url(self):
        return reverse('webapp:car_detail', kwargs={"pk": self.object.car.pk})


class CarCreateView(PermissionRequiredMixin, CreateView):
    model = Car
    form_class = CarForm
    template_name = "cars/create.html"
    permission_required = "webapp.add_car"

    def get_form(self, form_class=None):
        form = super().get_form()
        form.helper.form_action = 'webapp:car_create'
        return form

    def get_object(self, queryset=None):
        pk = self.kwargs.get("pk")
        return get_object_or_404(Car, pk=pk)

    def get_success_url(self):
        return reverse('webapp:car_detail', kwargs={"pk": self.object.pk})


class CarDeleteView(PermissionRequiredMixin, DeleteView):
    model = Car
    template_name = "cars/delete.html"
    success_url = reverse_lazy("webapp:index")
    permission_required = "webapp.delete_car"


class PhotoCreateView(PermissionRequiredMixin, CreateView):
    model = Photo
    template_name = "cars/photo_form.html"
    form_class = PhotoForm
    permission_required = "webapp.add_photo"

    def form_valid(self, form):
        form.instance.car = self.get_object()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context["pk"] = self.kwargs.get("pk")
        return context

    def get_object(self, queryset=None):
        pk = self.kwargs.get("pk")
        return get_object_or_404(Car, pk=pk)

    def get_success_url(self):
        return reverse('webapp:car_detail', kwargs={"pk": self.object.car.pk})

rent/webapp/views/general_view.py
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import View, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin

from webapp.forms import ClientForm
from webapp.models import Client


class IndexView(View):
    def get(self, request, *args, **kwargs):
        return render(request, "general/index.html")


class AboutUsView(View):
    def get(self, request, *args, **kwargs):
        return render(request, "general/about_us.html")


class ContactView(LoginRequiredMixin, CreateView):
    model = Client
    template_name = 'general/contacts.html'
    form_class = ClientForm

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_form(self, form_class=None):
        form = super().get_form()
        form.helper.form_action = 'webapp:contacts'
        return form

    def get_success_url(self):
        return reverse('webapp:index')

rent/webapp/templates/base.html
{% load static %}
{% load i18n %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.6.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static "font-awesome-4.7.0/css/font-awesome.min.css" %}">
    <link rel="stylesheet" href="{% static "css/main.css" %}">
    <title>{% trans "titleCarRent" %}</title>
</head>
<body>
    {% block header %}
            <div class="pos-f-t">
              <div class="collapse" id="navbarToggleExternalContent">
                <div class="bg-dark p-4">
                    <div class="d-flex flex-column align-items-center">
                        <a class="text-light" href="{% url "webapp:about_us" %}">{% trans "aboutCompanyMenu" %}</a>
                        <a class="text-light" href="http://localhost:8000/#our">{% trans "OurServiceMenu" %}</a>
                        <a class="text-light" href="{% url "webapp:car_list" %}">{% trans "CarParkMenu" %}</a>
                        <a class="text-light" href="{% url "webapp:contacts" %}">{% trans "ContactsMenu" %}</a>
                    </div>
                </div>
              </div>
              <nav class="navbar navbar-dark bg-dark">
                  <div class="d-flex justify-content-between align-items-center w-100 p-2">
                      <div class="menu_but d-flex justify-content-between align-items-center">
                        <button class="navbar-toggler" type="button" data-toggle="collapse"
                            data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                            {% trans "MenuBtn" %}
                        </button>
                      </div>
                <li class="nav-item dropdown">
                    {% get_current_language as LANGUAGE_CODE %}
                    {% get_available_languages as LANGUAGES %}
                    {% get_language_info_list for LANGUAGES as languages %}
                    {% get_language_info for LANGUAGE_CODE as current_language %}
                    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">
                        {{ current_language.name_local }}
                    </a>
                    <div class="dropdown-menu">
                        {% for language in languages %}
                            <a href="/{{ language.code }}" class="dropdown-item">
                                {{ language.name_local }}({{ language.code }})
                            </a>
                        {% endfor %}
                    </div>
                </li>
                      <a class="logo_link navbar-brand" href="{% url "webapp:index" %}">
                        <i class="fa fa-car fa-2x" aria-hidden="true"></i>
                        Garage Rent
                      </a>
                    <div class="d-flex align-items-center justify-content-between login_container">
                        {% if user.is_authenticated %}
                                <a class="text-light" href="{% url "accounts:profile" user.pk %}">{% trans "Hello" %}, {{ user.username }}</a>
                                <form action="{% url "accounts:logout" %}" method="post">
                                    {% csrf_token %}
                                    <button class="btn btn-link text-light">{% trans "Logout" %}</button>
                                </form>
                        {% else %}
                            <a class="text-light" href="{% url "accounts:login" %}?next={{ request.get_full_path }}">{% trans "login" %}</a>
                            <a class="text-light" href="{% url "accounts:register" %}?next={{ request.get_full_path }}">{% trans "SignUp" %}</a>
                        {% endif %}
                      <p class="text-light">
                          +7 705 444 46 44 <br>
                          +7 708 600 76 36 <br>
                          com.garage19@gmail.com
                      </p>
                    </div>
                  </div>
              </nav>
            </div>
    {% endblock %}

    {% block carousel %}
    {% endblock %}

        {% block card %}
        {% endblock %}

    <div class="content">
        {% block content %}
        {% endblock %}
    </div>
    <footer class="bg-dark">
        {% block footer %}
            <div class="d-flex justify-content-between text-light">
                <p>© 2019-2021 Garage Rent</p>
                <div class="d-flex justify-content-between link_net footer_block">
                    <a href="https://www.instagram.com/?hl=ru" class="text-light"><i class="bi bi-instagram"></i></a>
                    <a href="https://t.me/+77054444644" class="text-light"><i class="bi bi-telegram"></i></a>
                    <a href="https://api.whatsapp.com/send?phone=77054444644" class="text-light"><i class="bi bi-whatsapp"></i></a>
                </div>
                <p class="fst-italic">
                    Designed by Kifolga. All rights reserved.
                </p>
            </div>
        {% endblock %}
    </footer>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity=
        "sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script>
        function myMap() {
          var mapCanvas = document.getElementById("map");
          var mapOptions = {
            center: new google.maps.LatLng(51.5, -0.2), zoom: 10
          };
          var map = new google.maps.Map(mapCanvas, mapOptions);
        }
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDR8P72HMX3zllKeeZt8X89dJWMEu0LSX8&callback=myMap" async defer></script>
</body>
</html>