rent/accounts/urls.py
from django.urls import path
from accounts import views as accounts_views

app_name = "accounts"

urlpatterns = [
    path("login/", accounts_views.LoginView.as_view(), name="login"),
    path("logout/", accounts_views.LogoutView.as_view(), name="logout"),
    path("create/", accounts_views.RegisterView.as_view(), name="register"),
    path("<int:pk>/", accounts_views.UserDetailView.as_view(), name="profile"),
    path("profile/<int:pk>/edit", accounts_views.UserChangeView.as_view(), name="edit_profile"),
    path("profile/<int:pk>/change_password", accounts_views.ChangePasswordView.as_view(), name="change_password")
]

rent/rent/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

]

urlpatterns += i18n_patterns(
    path("", include("webapp.urls")),
    path("accounts/", include("accounts.urls"))
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rent/accounts/models.py
from django.db import models
from django.contrib.auth import get_user_model


class Profile(models.Model):
    user = models.OneToOneField(get_user_model(), related_name='profile', on_delete=models.CASCADE,
                                verbose_name='Пользователь')
    about_me = models.TextField(max_length=3000, null=True, blank=True, verbose_name="Обо мне")
    avatar = models.ImageField(null=True, blank=True, upload_to='user_pics', verbose_name='Аватар')
    birth = models.DateField(null=True, blank=True)

rent/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model, update_session_auth_hash
from django.contrib.auth.forms import UserCreationForm

from accounts.models import Profile


class RegistrationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        fields = ["username", "first_name",
                  "last_name", "email", "password1", "password2"]


class UserChangeForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ["first_name", "last_name", "email"]
        labels = {"first_name": "Имя", "last_name": "Фамилия", "email": "Email"}


class ProfileChangeForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ["user"]


class PasswordChangeForm(forms.ModelForm):
    old_password = forms.CharField(label="Old password", strip=False,
                                   widget=forms.PasswordInput)
    password = forms.CharField(label="Password", strip=False,
                               widget=forms.PasswordInput)
    password_confirm = forms.CharField(label="Confirm password", strip=False,
                                       widget=forms.PasswordInput)

    def clean_password_confirm(self):
        password = self.cleaned_data["password"]
        password_confirm = self.cleaned_data["password_confirm"]
        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError("Passwords are not equal")
        return password_confirm

    def clean_old_password(self):
        old_password = self.cleaned_data["old_password"]
        if not self.instance.check_password(old_password):
            raise forms.ValidationError("Wrong old password")
        return old_password

    def save(self, commit=True):
        user = self.instance
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()

        return user

    class Meta:
        model = get_user_model()
        fields = ["old_password", "password", "password_confirm"]

rent/accounts/views.py
from django.conf import settings
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import View, CreateView, DetailView, UpdateView
from django.http import HttpResponseRedirect
from django.core.paginator import Paginator
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth import get_user_model, update_session_auth_hash

from accounts.forms import RegistrationForm, UserChangeForm, ProfileChangeForm, PasswordChangeForm
from accounts.models import Profile


class LoginView(View):
    def get(self, request, *args, **kwargs):
        return render(request, "registration/login.html")

    def post(self, request, *args, **kwargs):
        username = request.POST.get("username")
        password = request.POST.get("password")
        next_path = request.POST.get("next")
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            if next_path:
                return HttpResponseRedirect(next_path)

            return redirect(settings.LOGIN_REDIRECT_URL)
        return render(request, "registration/login.html", {"has_error": True})


class LogoutView(View):
    def post(self, request, *args, **kwargs):
        logout(request)
        return redirect(settings.LOGOUT_REDIRECT_URL)


class RegisterView(CreateView):
    model = User
    template_name = "registration/register.html"
    form_class = RegistrationForm

    def form_valid(self, form):
        user = form.save()
        Profile.objects.create(user=user)
        login(self.request, user)
        return redirect("webapp:index")


class UserDetailView(LoginRequiredMixin, DetailView):
    model = get_user_model()
    template_name = "user_detail.html"
    context_object_name = "user_obj"
    paginate_related_by = 5
    paginate_related_orphans = 0

    def get_context_data(self, **kwargs):
        clients = self.object.clients.order_by("-created_at")
        paginator = Paginator(clients, self.paginate_related_by,
                              orphans=self.paginate_related_orphans)
        page_num = self.request.GET.get("page", 1)
        page = paginator.get_page(page_num)
        kwargs["page_obj"] = page
        kwargs["clients"] = page.object_list
        kwargs["is_paginated"] = page.has_other_pages()
        return super().get_context_data(**kwargs)


class ChangeProfileAccessMixin(UserPassesTestMixin):
    def test_func(self):
        return self.request.user == self.get_object() or \
               self.request.user.is_superuser or self.request.user.groups.filter(name="admins")


class UserChangeView(ChangeProfileAccessMixin, UpdateView):
    model = get_user_model()
    form_class = UserChangeForm
    template_name = "user_change.html"
    context_object_name = "user_obj"

    def get_profile_form(self):
        form_kwargs = {"instance": self.object.profile}
        if self.request.method == "POST":
            form_kwargs["data"] = self.request.POST
            form_kwargs["files"] = self.request.FILES
        return ProfileChangeForm(**form_kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        user_form = self.get_form()
        profile_form = self.get_profile_form()
        if user_form.is_valid() and profile_form.is_valid():
            return self.form_valid(user_form, profile_form)
        else:
            return self.form_invalid(user_form, profile_form)

    def form_valid(self, user_form, profile_form):
        result = super().form_valid(user_form)
        profile_form.save()
        return result

    def form_invalid(self, user_form, profile_form):
        context = self.get_context_data(
            user_form=user_form,
            profile_form=profile_form
        )
        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        if "profile_form" not in kwargs:
            kwargs["profile_form"] = self.get_profile_form()
            kwargs["user_form"] = self.get_form()
        return super().get_context_data(**kwargs)

    def get_success_url(self):
        return reverse("accounts:profile", kwargs={"pk": self.object.pk})


class ChangePasswordView(ChangeProfileAccessMixin, UpdateView):
    model = get_user_model()
    form_class = PasswordChangeForm
    template_name = "change_password.html"
    context_object_name = "user_obj"

    def form_valid(self, form):
        form.save()
        update_session_auth_hash(self.request, form.instance)
        return redirect("accounts:profile", pk=self.get_object().pk)

rent/accounts/templates/change_password.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_filters %}

{% block title %}{% trans "ChangePassword" %}{% endblock %}

{% block content %}
    <div class="change_password">
        <h1>{% blocktrans %}Change password for {% endblocktrans %} {{ user_obj.username }}</h1>
        <form action="{% url "accounts:change_password" user_obj.pk %}" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn-primary my-5">{% trans "Change" %}</button>
        </form>
    </div>
{% endblock %}

rent/accounts/templates/user_change.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% load i18n %}

{% block title %}{% endblock %}

{% block content %}
    <div class="my-5 mx-auto">
        <h1>{% trans "ChangeProfile" %}</h1>
        <form
                action="{% url "accounts:edit_profile" user_obj.pk %}"
                method="post"
                enctype="multipart/form-data"
        >
            {% csrf_token %}
            {{ user_form|crispy }}
            {{ profile_form|crispy }}
            <button class="btn btn-primary my-5">{% trans "ChangeBtn" %}</button>
        </form>
    </div>
{% endblock %}

rent/accounts/templates/user_detail.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% endblock %}

{% block content %}
    <div class="my-5 d-flex justify-content-between text-items-center">
        <h1 class="w-50">{% trans "Profile" %} {{ user_obj.username }}</h1>
        <div class="w-50">
            {% ifequal user user_obj %}
                <p>
                    <a href="{% url "accounts:edit_profile" user_obj.pk %}"
                       class="border border-radius-1 p-3 bg-secondary text-white">
                         {% trans "ChangeProfile" %}
                    </a>
                    <a href="{% url "accounts:change_password" user_obj.pk %}"
                       class="border border-radius-1 p-3 bg-secondary text-white">
                         {% trans "ChangePassword" %}
                    </a>
                </p>
            {% endifequal %}
        </div>
    </div>
    <div class="d-flex justify-content-between">
        <div class="w-50">
            {% if user_obj.profile.avatar %}
                <img src="{{ user_obj.profile.avatar.url }}" width="250">
            {% else %}
                <img src="https://thumbs.dreamstime.com/b/default-avatar-profile-vector-user-profile-default-avatar-profile-vector-user-profile-profile-179376714.jpg" width="250">
            {% endif %}
        </div>
        <div class="my-5 w-50">
            <p>{% trans "Username" %}: {{ user_obj.username }}</p>
            <p>{% trans "Firstname" %}: {{ user_obj.first_name }}</p>
            <p>{% trans "Lastname" %}: {{ user_obj.last_name }}</p>
            <p>{% trans "Birth" %}: {{ user_obj.profile.birth }}</p>
        </div>
    </div>
        <div class="my-5">
        <h2 class="my-5">{% blocktrans %}Заявки пользователя{% endblocktrans %}</h2>
        <hr>
        {% if is_paginated %}
            {% include "partial/pagination.html" %}
        {% endif %}
        <div>
            {% for client in user_obj.clients.all %}
                <p>{% trans "Заявка" %}: {{ client.message }}</p>
                <p>{{ client.created_at }}</p>
            {% endfor %}
        </div>
        {% if is_paginated %}
            {% include "partial/pagination.html" %}
        {% endif %}
    </div>
{% endblock %}